### PR TITLE
[PDI-14959] Data Lineage: Table Output step analyzer does not add default fields to the lineage output

### PR DESCRIPTION
**Pull request by mr9d**
- Use output field names if database fields is not specified
- UTs

### CODE REVIEW

**Comment by mr9d** [comment]
@rfellows please review.

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f core/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f core/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzer.java
  core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzerTest.java
  core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/transexecutor/TransExecutorStepAnalyzerTest.java

Unit test coverage change:
============
org.pentaho.metaverse.analyzer.kettle.step.tableoutput.TableOutputStepAnalyzer:
 * Branch Change :  + 2.80%
 * Complexity Change :  + .95%
 * Instruction Change :  + .10%
 * Line Change :  + .06%

org.pentaho.metaverse.impl.MetaverseCompletionService:
 * Branch Change :  + 16.67%
 * Complexity Change :  + 8.33%

Integration test coverage change:
============
org.pentaho.metaverse.analyzer.kettle.step.tableoutput.TableOutputStepAnalyzer:
 * Branch Change : **-.35%**
 * Complexity Change : **-.95%**
 * Instruction Change :  + .33%
 * Line Change :  + .53%

org.pentaho.metaverse.graph.BlueprintsGraphMetaverseReader:
 * Branch Change :  + 6.12%
 * Complexity Change :  + 4.69%
 * Instruction Change :  + 9.03%
 * Line Change :  + 8.42%

License header violations:
==========================
1. Copyright year is not the current year on core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzer.java. Found 2015. Was expecting 2016
2. Copyright year is not the current year on core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzerTest.java. Found 2015. Was expecting 2016
3. Copyright year is not the current year on core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/transexecutor/TransExecutorStepAnalyzerTest.java. Found 2015. Was expecting 2016

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzer.java

1. Message: 'if' is not followed by whitespace. at Line: 129 Column: 7

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f core/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f core/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzer.java
  core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzerTest.java
  core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/transexecutor/TransExecutorStepAnalyzerTest.java

Unit test coverage change:
============
org.pentaho.metaverse.analyzer.kettle.step.tableoutput.TableOutputStepAnalyzer:
 * Branch Change :  + 2.80%
 * Complexity Change :  + .95%
 * Instruction Change :  + .10%
 * Line Change :  + .06%

Integration test coverage change:
============
org.pentaho.metaverse.analyzer.kettle.step.tableoutput.TableOutputStepAnalyzer:
 * Branch Change : **-.35%**
 * Complexity Change : **-.95%**
 * Instruction Change :  + .33%
 * Line Change :  + .53%

License header violations:
==========================
1. Copyright year is not the current year on core/src/main/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzer.java. Found 2015. Was expecting 2016
2. Copyright year is not the current year on core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/tableoutput/TableOutputStepAnalyzerTest.java. Found 2015. Was expecting 2016
3. Copyright year is not the current year on core/src/test/java/org/pentaho/metaverse/analyzer/kettle/step/transexecutor/TransExecutorStepAnalyzerTest.java. Found 2015. Was expecting 2016

**Comment by rfellows** [comment]
It is my recollection that if you do not specify the fields names in Table Output, that the fields are inserted into the table positionally, not by name. can you confirm or refute that?

If they are inserted positionally, then we can't make this assumption.

Also, please fix the license headers

**Comment by mr9d** [comment]
@rfellows from the results of my tests, fields are inserted by the Table Output component according to their names (not positionally).

pdi-14959-column-order

 License headers is fixed.

**Comment by rfellows** [comment]
Excellent, thanks for verifying that

**Pull request merged**
