### PR TITLE
[BACKLOG-29894] update pdi to show metaverse log statements

### PR DESCRIPTION
**Pull request by NJtwentyone**

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 3 test(s) failed:

- **org.pentaho.metaverse.analyzer.kettle.extensionpoints.job.JobRuntimeExtensionPointTest.testJobFinished**
```
Central Log Store is not initialized!!!
```
- **org.pentaho.metaverse.analyzer.kettle.extensionpoints.job.JobRuntimeExtensionPointTest.testJobFinishedNotAsync**
```

Mockito cannot mock this class: class org.pentaho.metaverse.analyzer.kettle.extensionpoints.job.JobLineageHolderMap$$EnhancerByMockitoWithCGLIB$$b44fa4aa
Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.
```
- **org.pentaho.metaverse.analyzer.kettle.extensionpoints.job.JobRuntimeExtensionPointTest.testJobFinishedAsync**
```

Mockito cannot mock this class: class org.pentaho.metaverse.analyzer.kettle.extensionpoints.job.JobLineageHolderMap$$EnhancerByMockitoWithCGLIB$$b44fa4aa
Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.
```
---

|Total|Failed|Skipped|
|---|---|---|
|888|3|0|

|[Details](http://ciren.pentaho.net/job/wingman/job/projects/job/metaverse-plugin/job/PR-601/1/testReport)|
|----|

**Comment by buildguy** [comment]
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 3 test(s) failed:

- **org.pentaho.metaverse.analyzer.kettle.extensionpoints.job.JobRuntimeExtensionPointTest.testJobFinished**
```
Central Log Store is not initialized!!!
```
- **org.pentaho.metaverse.analyzer.kettle.extensionpoints.job.JobRuntimeExtensionPointTest.testJobFinishedNotAsync**
```

Mockito cannot mock this class: class org.pentaho.metaverse.analyzer.kettle.extensionpoints.job.JobLineageHolderMap$$EnhancerByMockitoWithCGLIB$$e9c0fd65
Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.
```
- **org.pentaho.metaverse.analyzer.kettle.extensionpoints.job.JobRuntimeExtensionPointTest.testJobFinishedAsync**
```

Mockito cannot mock this class: class org.pentaho.metaverse.analyzer.kettle.extensionpoints.job.JobLineageHolderMap$$EnhancerByMockitoWithCGLIB$$e9c0fd65
Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.
```
---

|Total|Failed|Skipped|
|---|---|---|
|888|3|0|

|[Details](http://ciren.pentaho.net/job/wingman/job/projects/job/metaverse-plugin/job/PR-601/2/testReport)|
|----|

**Comment by NJtwentyone** [comment]
Ignore Sonar Code Analysis failure

I only added/modified 10 lines of code, all were either:
- log statement
- declaring variable

correct url for Quality Gate failure is : http://svpxbldcn7snr1.pentaho.net:9000/dashboard?id=pentaho%3Apentaho-metaverse&pullRequest=601

**Comment by NJtwentyone** [comment]
please review @pentaho/r2d2

**Pull request merged**
