### PR TITLE
[PDI-19135] Multiple Passwords are exposed in plaintext when using data lineage

### PR DESCRIPTION
**Pull request by moraesvc**
@bcostahitachivantara 
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **892**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/metaverse-plugin/job/PR-645/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **892**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/metaverse-plugin/job/PR-645/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **892**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/metaverse-plugin/job/PR-645/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core
```
---
:ok_hand: All tests passed!
 
Tests run: **1174**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/metaverse-plugin/job/PR-645/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core
```
---
:ok_hand: All tests passed!
 
Tests run: **1174**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/metaverse-plugin/job/PR-645/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core
```
---
:ok_hand: All tests passed!
 
Tests run: **1174**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/metaverse-plugin/job/PR-645/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core
```
---
:ok_hand: All tests passed!
 
Tests run: **1174**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/metaverse-plugin/job/PR-645/8/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core
```
---
:ok_hand: All tests passed!
 
Tests run: **1174**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/metaverse-plugin/job/PR-645/9/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by bcostahitachivantara — APPROVED** [review]

**Pull request merged**
