### PR TITLE
[PDI-14888] Data Lineage is creating wrong connection information

### PR DESCRIPTION
**Pull request by mr9d**
- adding "databaseName" to the LogiclaIdGenerator for JDBC node
- new unit test.

### CODE REVIEW

**Comment by rfellows** [comment]
i'm concerned about failing integration tests. they should all pass. while it might not seem related on the surface something is most likely wrong an needs fixed

**Comment by mr9d** [comment]
Rob, as I see, all failures are exist in 6.1 branch and there is no way they can be caused by this changes. 

I will be able to take a closer look on them next Monday.

**Comment by rfellows** [comment]
i am not suggesting that you broke them, only that they need to be fixed.

I'll merge this now with the understanding that the tests get fixed next week.

**Comment by lucboudreau** [comment]
> the tests get fixed next week

I will also be looking out for this.

**Pull request merged**
