### PR TITLE
PDI-14888 Data Lineage is creating wrong connection information

### PR DESCRIPTION
**Pull request by mr9d**
- Adding PROPERTY_NAME to LogicalIdGenerator for JDBC node.

### CODE REVIEW

**Comment by mr9d** [comment]
@rfellows please review.

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f api/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f api/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  api/src/main/java/org/pentaho/dictionary/DictionaryConst.java

null

null

**Comment by rfellows** [comment]
Actually, this is NOT correct. The LogicalID is what makes an entity LOGICALLY UNIQUE. The connection name should not be considered part of the logical ID. technically they are the same connection information, connecting with the same jdbc connection settings. the name is something we give to it. I understand the confusion, but it's how we can identify things being the same across ktr's/kjb's even though the seem different.

maybe the solution is to change the displayed text in the graph to be some connection string made up of the logical id bits to make it more clear as to what is going on.

**Comment by mr9d** [comment]
@rfellows should we use "databaseName" property instead? That might work as well.

**Comment by rfellows** [comment]
please squash the commits into a single commit.
also, i can't tell by the wingman run, but do all of the integration tests still pass?

**Comment by mr9d** [comment]
Done, this is a new pull request with a single commit: https://github.com/pentaho/pentaho-metaverse/pull/410

As for integration tests, There are some failures when I ran them locally, but nothing new and related to my changes.

**Pull request closed without merging**
